development:
  password: ba001d3a442772f2a55d8e521f980ec6
  theme_id: "174256079"
  store: nanocomposix-2017.myshopify.com
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"
    - "(A Document Being Saved By Coda)"
    - ".smbdelete*"
    - "._*"